### ISSUE TITLE
Ajustes na página inicial

### ISSUE THREAD

**Issue by tonetlds** [jefersondiniz/wsmoveisplanejados#1]
- [x] Logo: Diminuir um pouco
- [x] Reposicionar imagens (acredito que ``background-position: center center;`` já resolva)
- [x] Adicionar seção com o selo e frase (slogan, em verde no print)
- [x] Alterar **cor** e **background** dos boxes

![site 1](https://cloud.githubusercontent.com/assets/2693019/15042586/af2e6b94-129b-11e6-84d8-42a78f1f6d77.jpg)

**Comment by jefersondiniz** [comment]
Por favor me informar as cores dos boxes

**Comment by tonetlds** [comment]
Amarelo:  #ffcb05
Azul:        #3fbbb3

**Comment by tonetlds** [comment]
- [ ] Fontes dos banners
- [ ] Backgrounds (textura)
- [ ] Tamanho selo

Corrigido...

![image](https://cloud.githubusercontent.com/assets/2693019/15127559/8f966d16-160d-11e6-9d5c-6c7da5cb5223.png)
