### ISSUE TITLE
Página "Monte seu ambiente"

### ISSUE THREAD

**Issue by tonetlds** [jefersondiniz/wsmoveisplanejados#11]
A página monte seu ambiente será apenas uma landing page com um botão/link levando para o site do mooble.com..

Aumenta a seção onde tem a foto de fundo e remove o resto, deixando somente o título com fundo branco. E dentro da seção com imagem de fundo coloca uma frase e um botão bem grande.

O link deve direcionar para http://mooble.com/wsmoveisplanejados 

![capturar](https://cloud.githubusercontent.com/assets/2693019/15298871/eb7944b8-1b77-11e6-99b0-985360e15b98.PNG)

**Comment by jefersondiniz** [comment]
Concluido !
