### ISSUE TITLE
Página Contato

### ISSUE THREAD

**Issue by tonetlds** [jefersondiniz/wsmoveisplanejados#12]
Colocar endereço e telefone na página de contato.
Corrigir local exibido no mapa.

![capturar](https://cloud.githubusercontent.com/assets/2693019/15299009/c6e0b3ec-1b78-11e6-8fe6-a2d1081ccd2a.PNG)

**Comment by jefersondiniz** [comment]
Concluido, esse endereço não consta no google maps, apenas coloquei o Nova Prata, RS
