### ISSUE TITLE
Alterar logo

### ISSUE THREAD

**Issue by tonetlds** [jefersondiniz/wsmoveisplanejados#4]
Ficou com falha.
Aline vai gerar arquivo no tamanho certo.

**Comment by jefersondiniz** [comment]
Logo onde esta? por onde anda ? será que ela existe ? onde está ?

**Comment by jefersondiniz** [comment]
Logo onde esta ? ela existe ? por onde anda ?

**Comment by tonetlds** [comment]
Segue logo para o topo...
https://www.dropbox.com/s/aog8i1w08peiisn/logo_topo.png?dl=1

**Comment by jefersondiniz** [comment]
Logo alterada
