### ISSUE TITLE
Alterar fonte principal

### ISSUE THREAD

**Issue by tonetlds** [jefersondiniz/wsmoveisplanejados#6]
Trocar a fonte principal do site (de todos os textos) pela **Champagne & Limousines**

**Comment by jefersondiniz** [comment]
Fonte principal alterada para Champagne & Limousines

**Comment by tonetlds** [comment]
Primeiro teste ja não rolou...

![image](https://cloud.githubusercontent.com/assets/2693019/15200510/040ae8aa-17be-11e6-88a5-b571c9c96494.png)

Tem q pôr o font-family que está no arquivo **fonts/fonts.css**:

`font-family: 'champagne__limousinesbold';`
