### ISSUE TITLE
Recolocar a frase do banner principal

### ISSUE THREAD

**Issue by tonetlds** [jefersondiniz/wsmoveisplanejados#7]
A frase do banner principal não está mais aparecendo.
Acredito que você removeu porque na imagem que ela mandou não tinha mesmo, mas estava só representando o posicionamento correto da imagem.

![image](https://cloud.githubusercontent.com/assets/2693019/15128022/d6a2bed8-160f-11e6-9798-8d2feccadbe0.png)

**Comment by jefersondiniz** [comment]
Frase adicionada novamente.
